include:
    "config.py"

all_genomes = ['galGal4','melGal1',
               'taeGut2', 'geoFor1',
               'melUnd1', 'mm10',
               'hg38', 'allMis1',
               'chrPic2', 'anoCar2',
               'xenTro7', 'danRer7',
               'petMar2'
              ]
rule all:
    input:
        "raw_data/191way.nh",
        "raw_data/103way.nh",
        "raw_data/172way.nh",
        "processed_data/pruned191.nh",
        "processed_data/pruned103.nh",
        "processed_data/pruned172.nh"

rule download_191way:
    output: "raw_data/191way.nh"
    shell: "wget -O {output} 'http://genome-source.cse.ucsc.edu/gitweb/?p=kent.git;a=blob_plain;f=src/hg/utils/phyloTrees/191way.nh;hb=HEAD'"

rule download_103way:
    output: "raw_data/103way.nh"
    shell: "wget -O {output} 'http://genome-source.cse.ucsc.edu/gitweb/?p=kent.git;a=blob_plain;f=src/hg/utils/phyloTrees/103way.nh;hb=HEAD'"

rule download_172way:
    output: "raw_data/172way.nh"
    shell: "wget -O {output} 'http://genome-source.cse.ucsc.edu/gitweb/?p=kent.git;a=blob_plain;f=src/hg/utils/phyloTrees/172way.nh;hb=HEAD'"

rule prune_all:
    input: "raw_data/191way.nh"
    output: "processed_data/pruned191.nh"
    run:
        genomes = (',').join(all_genomes)
        shell("tree_doctor --prune-all-but {genomes} {input} > {output}")


rule prune_103:
    input: "raw_data/103way.nh"
    output: "processed_data/pruned103.nh"
    run:
        genomes = (',').join(all_genomes)
        shell("tree_doctor --prune-all-but {genomes} {input} > {output}")


rule prune_172:
    input: "raw_data/172way.nh"
    output: "processed_data/pruned172.nh"
    run:
        genomes = (',').join(all_genomes)
        shell("tree_doctor --prune-all-but {genomes} {input} > {output}")


